### ISSUE TITLE
Avoid PHPSESSID

### ISSUE THREAD

**Issue by Blaztix** [byjg/jwt-session#10]
You can avoid create PHPSESSID cookie, adding before start session

    ini_set("session.use_cookies", 0);

I really don't know if this is recommended, but its works.

**Comment by byjg** [comment]
This will pass the PHPSESSID as a get parameter, am i correct?

In fact, the PHPSESSID is not necessary in the `jwt-session` because we are setting another cookie named `COOKIE_PREFIX_*`. 

We recently enforced the security based on the issue #8.

**Comment by Blaztix** [comment]
This avoid create the pointless cookie, phpsessid

**Comment by byjg** [comment]
I did some tests and seems to work. I'll do more tests here to see if everything is OK. Let me know if it is working for you also.

**Comment by byjg** [comment]
Use the follow configuration in your composer.json to test it. 

```
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "byjg/jwt-session": "2.0.0.x-dev"
    },
```

**Comment by Blaztix** [comment]
I test on 2.0.0 but it does not seem to works


but when I start it like this, works

    ini_set("session.use_cookies", 0);
    $sessionConfig = (new \ByJG\Session\SessionConfig('domain'))
        ->withSecret('My KEY :D ! ')
        ->withTimeoutMinutes(60 * 24 * 5)
        ->withCookie('.domain', '/');

Works, in __construct, when session system is initiated

    public function __construct($sessionConfig)
    {
        ini_set("session.use_cookies", 0);
        if (!($sessionConfig instanceof SessionConfig)) {
            throw new JwtSessionException('Required SessionConfig instance');
        }
        $this->sessionConfig = $sessionConfig;
    }

**Comment by byjg** [comment]
OK. Code updated with this.

**Comment by byjg** [comment]
I'll release soon this new version. Note that I moved the method `replaceSessionHandler` from `JwtSession` to `SessionConfig`. Take a look in the README.md.

**Comment by byjg** [comment]
Done. Release 2.0.0 created.
