### ISSUE TITLE
Function withSecret including decode argument

### ISSUE THREAD

**Issue by romulorosa** [byjg/jwt-session#14]
Hi @byjg, first of all I would like to thank you for publishing this library. It is working fine in one of my projects. However, I was trying to share the generated token with some other microservices in Python and I spent few hours debugging a problem which has appeared during the token verification. The two libraries expect different keys "formats" on their implementation. By default your library expect that the key will be encoded and the Python lib not. 
I would like to ask you, what do you think about including a parameter on `\ByJG\Session\SessionConfig::withSecret` to pass an option if the key should be decoded or not? Because I checked and the other library `jwt-wrapper` already has this parameter `implemented on \ByJG\Util\JwtKeySecret::__construct`. I would be happy to contribute even not being a PHP expert :sweat_smile: 

I have more questions and some ideas, do you suggest a different way to discuss them or shall I keep opening some "issues"?

**Comment by byjg** [comment]
Hello @romulorosa , I am glad to know that this library has been useful to you. I think your suggestion makes sense, and if you want to implement this by yourself I'd happy!

My suggestion, however, is to use the method name `withEncodedKey(true|false)` and the default for that is `true` to avoid break compatibility with previous versions. 

And about suggestions, questions and ideas, you can open an issue for each one.

**Comment by romulorosa** [comment]
@byjg Cool! I will try to implement these changes as soon as I can and then open a PR. Meanwhile, I was thinking about making a small change on the README just make it more clear that the key should be encoded.

**Comment by romulorosa** [comment]
As I mentioned... https://github.com/byjg/jwt-session/pull/15

**Comment by byjg** [comment]
Merged :) Thanks,
