### ISSUE TITLE
Request to Update byjg/jwt-session to Support firebase/php-jwt (^6.3.2)

### ISSUE THREAD

**Issue by newpen** [byjg/jwt-session#17]
Hi,

I'm currently using byjg/jwt-session in a project, and I’ve encountered a dependency conflict due to the current version of firebase/php-jwt required by byjg/jwt-session. The conflict arises because byjg/jwt-session depends on firebase/php-jwt ^5.0, while other packages in my project, such as kreait/firebase-php, require firebase/php-jwt ^6.3.2.

Could you please consider updating byjg/jwt-session to support firebase/php-jwt ^6.3.2? This update would help resolve the dependency conflict and allow byjg/jwt-session to be used alongside other packages that require the newer version of firebase/php-jwt.

Thanks a lot!

**Comment by byjg** [comment]
Hi, I will check this and and get back to you soon.

**Comment by byjg** [comment]
Hello, I've upgraded the package to use `firebase/php-jwt` to `^6` and small other changes. 

With that changes, I dropped support for PHP 7.4 and lower. 
https://github.com/byjg/php-jwt-session/releases/tag/4.9.0

You need to upgrade `jwt-session` in your compose, from to `2.0.0` to `4.9.*`

Thank you.

**Comment by newpen** [comment]
Thank you very much!!
