### ISSUE TITLE
Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by Blaztix** [byjg/jwt-session#4]
I am using hybridauth and this can't store the variable in $_SESSION

**Comment by byjg** [comment]
Hi, the `$_SESSION` can hold a lot of objects. The JWT Session serialize the object before to set it. Could you explain to me your problem?

**Comment by Blaztix** [comment]
Of course!

I am testing a web app that uses:
`hybridauth/hybridauth`

So, the app works without any problem, but when I try to uses `byjg/jwt-session` I have the next error when I do a login with facebook for example.


	Fatal error
	Uncaught exception: 'Error' 
	Message: 'Cannot use object of type stdClass as array' 
	Stack trace:
	#0 /home/server/app_folder/vendor/hybridauth/hybridauth/src/Adapter/DataStoreTrait.php(54): Hybridauth\Storage\Session->get('google.refresh_...')
	#1 /home/server/app_folder/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php(279): Hybridauth\Adapter\AbstractAdapter->getStoredData('refresh_token')
	#2 /home/server/app_folder/vendor/hybridauth/hybridauth/src/Provider/Google.php(80): Hybridauth\Adapter\OAuth2->initialize()
	#3 /home/server/app_folder/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php(113): Hybridauth\Provider\Google->initialize()
	#4 /home/server/app_folder/vendor/hybridauth/hybridauth/src/Hybridauth.php(141): Hybridauth\Adapter\AbstractAdapter->__construct(Array, NULL, NULL, NULL)
	#5 /home/server/app_folder/vendor/hybridauth/hybridauth/src/Hybridauth.php(241): Hybridauth\Hybridauth->getAdapter('Google')
	#6 /home/server/app_folder/App/Models/Publico.php(43): Hybridauth\Hybridauth->getConnectedAdapters()
	#7 /home/server/app_folder/App/Models/Publico/SocialLogin.php(230): App\Models\Publico->__construct()
	#8 /home/server/app_folder/App/Controllers/SocialLogin.php(25): App\Models\Publico\SocialLogin->__construct()
	#9 [internal function]: App\Controllers\SocialLogin->indexAction()
	#10 /home/server/app_folder/Core/Controller.php(48): call_user_func_array(Array, Array)
	#11 /home/server/app_folder/Core/Router.php(120): Core\Controller->__call('index', Array)
	#12 /home/server/app_folder/www/index.php(62): Core\Router->dispatch('socialLogin')
	#13 {main}

	Thrown in '/home/server/app_folder/vendor/hybridauth/hybridauth/src/Storage/Session.php' on line 58

And example of working SESSION FILE (without `byjg/jwt-session` obvisuly):

`HYBRIDAUTH::STORAGE|a:3:{s:8:"provider";N;s:21:"facebook.access_token";s:208:"verylongstring(208)";s:19:"facebook.token_type";s:6:"bearer";}login|b:1;hasPassword|b:1;name|s:12:"My Name";email|s:21:"my@email.com";user_id|i:2;`

Or as json

	{
		"HYBRIDAUTH::STORAGE":
			{
				"provider":null,
				"facebook.access_token":"verylongstring(208)",
				"facebook.token_type":"bearer"
			},
		"login":true,
		"hasPassword":true,
		"name":"My Name",
		"email":"my@email.com",
		"user_id":2
	}

I really don't know if the problem is with `hybridauth/hybridauth` or `byjg/jwt-session` but only happens when `byjg/jwt-session` is active

**Comment by byjg** [comment]
Could you provide a sample code? 

Probably you are running into in a specific situation and until now I could not reproduce it.

**Comment by Blaztix** [comment]
I use a MVC scheme, its can be a little tricky

### Publico.php
	...
	use Hybridauth\Hybridauth;
	class Publico extends My_app{

		var $config_social = __DIR__.'/Publico/config_social.php';
		public $hybridauth;
		public $adapters;
		public $loged = false;
		public function __construct() {
			parent::__construct();
			$handler = new \ByJG\Session\JwtSession('my_page.com', 'My_key!', 60*24*30);
			session_set_save_handler($handler, true);
			require $this->config_social;
			$this->hybridauth = new Hybridauth($config);
			$this->adapters = $this->hybridauth->getConnectedAdapters();
			$this->loged = (isset($_SESSION['login']) && $_SESSION['login']);
		}
	}

### SocialLogin.php

	<?php
	namespace App\Models\Publico;

	use PDO;
	use Hybridauth\Exception\Exception;
	use Hybridauth\Hybridauth;
	use Hybridauth\HttpClient;
	use Hybridauth\Storage\Session;

	class SocialLogin extends \App\Models\Publico {
		private $user = null;
		private $user_hasPassword = false;

		# ... many custom functions
		
		private function set_session() {
			$_SESSION['login'] = true;
			$_SESSION['hasPassword'] = $this->user_hasPassword;
			$_SESSION['name'] = $this->user['name'];
			$_SESSION['email'] = $this->user['email'];
			$_SESSION['user_id'] = $this->user['id'];
		}

		public function __construct() {
			parent::__construct();
			try {
				require $this->config_social;
				$hybridauth = new Hybridauth($config);
				$storage = new Session();
				$error = false;

				if (isset($_GET['provider'])) {
					// Validate provider exists in the $config
					if (in_array($_GET['provider'], $hybridauth->getProviders())) {
						// Store the provider for the callback event
						$storage->set('provider', $_GET['provider']);
					} else {
						$error = $_GET['provider'];
					}
				}

				# ... many custom functions

				if ($error) {
					$error_log('HybridAuth Error: Provider '. json_encode($error) .' not found or not enabled in $config');
					exit;
				}

				if ($provider = $storage->get('provider')) {

					$hybridauth->authenticate($provider);
					$storage->set('provider', null);

					// Retrieve the provider record
					$adapter = $hybridauth->getAdapter($provider);
					$userProfile = $adapter->getUserProfile();
					$accessToken = $adapter->getAccessToken();

					// add your custom AUTH functions (if any) here
					$data = (object) [
						'token'         => $accessToken,
						'identifier'    => $userProfile->identifier,
						'email'         => $userProfile->email,
						'first_name'    => $userProfile->firstName,
						'last_name'     => $userProfile->lastName,
						'display_name'  => $userProfile->displayName,
						'photoURL'      => strtok($userProfile->photoURL,'?'),
						];
					// ...
					if ($userProfile->email === null) {
						## msg
						$adapter->disconnect();
						exit();
					}

					$user = $this->get_user( $data->email ); #From Database
					if($user === null){
						# Database action
					} else {
						# Database action
					}

					//LOGIN
					//
					$this->user_hasPassword = !is_null($user['password']);
					$this->user = $user;
					$this->set_session();
				}

			} catch (Exception $e) {
				error_log( $e->getMessage());
				echo $e->getMessage();
			}
		}
	}

**Comment by Blaztix** [comment]
I printed the session variable at the moment of error, I got this:

	array (
	  'HYBRIDAUTH::STORAGE' => 
	  stdClass::__set_state(array(
	     'provider' => 'Facebook',
	     'facebook.authorization_state' => 'HA-6IZPO3VGNXSA19YUW8D4KQF52JCBLM7H0TER',
 	 )),
	);

And `Storage/Session.php` on line 58 is this.

	54 public function get($key)
	55	{
	56	$key = $this->keyPrefix . strtolower($key);
	57
	58        if (isset($_SESSION[$this->storeNamespace], $_SESSION[$this->storeNamespace][$key])) {
	59            return $_SESSION[$this->storeNamespace][$key];
	60	}
	61
	62	return null;
	63 }

so, If I understand, the problem is beacuse JWT reconstructs the variable and the set as an OBJECT and HYBRIDAUTH uses it as an ARRAY

**Comment by byjg** [comment]
Hi, I implemented some unit tests for this class here: https://github.com/byjg/jwt-session/tree/issue-4

I realize that during the conversion to JWT Token and get back the ARRAY TYPE is converted to stdClass as you can see in the failed test here: https://travis-ci.org/byjg/jwt-session/jobs/420097254

So, I have to figure out now how to guarantee the same object will be returned. 

Any ideas?

**Comment by byjg** [comment]
I found the issue. The problem is the JWTSession added an overhead for serialize / unserialize the session data. I removed this and worked. 

You can test by adding the follow version into your composer file: `dev-issue-4`

**Comment by Blaztix** [comment]
`dev-issue-4` works perfect, 

I had made this modification before, in `JwtSession.php` in function read

	141	if( $data->data->{'HYBRIDAUTH::STORAGE'})  $data->data->{'HYBRIDAUTH::STORAGE'} = (array) $data->data->{'HYBRIDAUTH::STORAGE'}

I think it can be fixed by doing a simple cycle and convert the necessary variables into an array.

But I think the `dev-issue-4` solution is better, it consumes less resources but unfortunately it requires more characters for the cookie.

Also I have a problem with send cookie and I fixed with some `session_write_close()` its strange because the functions is registered, thus, this fix also fix that apparently

**Comment by byjg** [comment]
Good to know! So, I will merge this branch and create a new release version.

I will notice you here once it is done.

**Comment by byjg** [comment]
Hi, thank you for your feedback. The release 1.0.2 is published. Please switch to it. The "dev-issue-4" version does not exists anymore.
