### ISSUE TITLE
Cookie set and delete error

### ISSUE THREAD

**Issue by Blaztix** [byjg/jwt-session#6]
Hi again :)

The cookie is always set with expires at "1969-12-31T23:59:59", so the **timeOutMinutes** is pointless

So I think the write function would be this:

	public function write($session_id, $session_data)
	{
		$jwt = new JwtWrapper($this->serverName, $this->secretKey);
		$data = $jwt->createJwtData($session_data, $this->timeOutMinutes * 60);
		$token = $jwt->generateToken($data);

		if (!headers_sent()) {
			setcookie(self::COOKIE_PREFIX . $this->suffix, $token, (time()+$this->timeOutMinutes*60) , '/', $this->cookieDomain);
			if (defined("SETCOOKIE_FORTEST")) {
				$_COOKIE[self::COOKIE_PREFIX . $this->suffix] = $token;
			}
		}

		return true;
	}

And the destroy function must have the **cookieDomain** in case of use, because set-cookie is ignore in case of using a domain

    public function destroy($session_id)
    {
        if (!headers_sent()) {
            setcookie(self::COOKIE_PREFIX . $this->suffix, null, (time()-3000) , '/', $this->cookieDomain);
        }

        return true;
    }

**Comment by byjg** [comment]
Great suggestion! I implemented your suggestions on the branch 1.0.3. Soon I'll create a release.

**Comment by byjg** [comment]
It was closed, at the wrong moment. After apply the PR#9 I'll close it.

**Comment by byjg** [comment]
Done
